<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>OrpheusORMInterfaces</PackageId>
    <Title>OrpheusORM Abstractions</Title>
    <Description>OrpheusORM abstractions (interfaces).</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\net9.0\OrpheusInterfaces.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net9.0\OrpheusInterfaces.xml</DocumentationFile>
  </PropertyGroup>

</Project>
