<Project>
   <PropertyGroup>
	   <Version>2.0.0</Version>
	   <Copyright>Mobilotronic</Copyright>
	   <AssemblyVersion>2.0.0</AssemblyVersion>
	   <FileVersion>2.0.0</FileVersion>
	   <Product>Orpheus ORM</Product>
   </PropertyGroup>

   <PropertyGroup>
	   <IsPackable>false</IsPackable>
	   <Authors>Mobilotronic</Authors>
	   <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
	   <PackageProjectUrl>https://github.com/mobilotronic/OrpheusORM</PackageProjectUrl>
	   <RepositoryUrl>https://github.com/mobilotronic/OrpheusORM</RepositoryUrl>
	   <RepositoryType>git</RepositoryType>
	   <PackageIcon>OrpheusIcon.png</PackageIcon>
	   <PackageReadmeFile>README.md</PackageReadmeFile>
   </PropertyGroup>

   <ItemGroup>
	   <None Include="$(MSBuildThisFileDirectory)Nuget\OrpheusIcon.png" Pack="true" PackagePath="\" Visible="false" Condition="Exists('$(MSBuildThisFileDirectory)Nuget\OrpheusIcon.png')" />
	   <None Include="$(MSBuildThisFileDirectory)ReadMe.md" Pack="true" PackagePath="README.md" Visible="false" Condition="Exists('$(MSBuildThisFileDirectory)ReadMe.md')" />
   </ItemGroup>
</Project>
