using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;

namespace OrpheusTests.SQLServerTests
{
    [TestClass]
    [TestCategory(BaseTestClass.SQLServerTests)]
    [DoNotParallelize]
    public class SQLServerDependencyInjectionTests : DependencyInjectionTests
    {
        [TestInitialize]
        public void Setup()
        {
            this.DatabaseEngine = DbEngine.dbSQLServer;
        }

        [TestMethod]
        public void SQLServerTestSchemaAndModuleResolveFromTheDatabase()
        {
            this.TestSchemaAndModuleResolveFromTheDatabase();
        }

        [TestMethod]
        public void SQLServerTestUnsizedStringModelGeneratesSchema()
        {
            this.TestUnsizedStringModelGeneratesSchema();
        }

        [TestMethod]
        public async Task SQLServerTestKeylessProjectionLoads()
        {
            await this.TestKeylessProjectionLoads();
        }

        [TestMethod]
        public void SQLServerTestKeylessModelCannotBeMutated()
        {
            this.TestKeylessModelCannotBeMutated();
        }

        [TestMethod]
        public async Task SQLServerTestAutoGeneratedKeysAreTimeOrdered()
        {
            await this.TestAutoGeneratedKeysAreTimeOrdered();
        }

        [TestMethod]
        public void SQLServerTestKeyGeneratorIsPluggable()
        {
            this.TestKeyGeneratorIsPluggable();
        }
    }
}
