using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;

namespace OrpheusTests.PostgreSQLTests
{
    [TestClass]
    [TestCategory(BaseTestClass.PostgreSQLTests)]
    [DoNotParallelize]
    public class PostgreSQLDependencyInjectionTests : DependencyInjectionTests
    {
        [TestInitialize]
        public void Setup()
        {
            this.DatabaseEngine = DbEngine.dbPostgreSQL;
        }

        [TestMethod]
        public void PostgreSQLTestSchemaAndModuleResolveFromTheDatabase()
        {
            this.TestSchemaAndModuleResolveFromTheDatabase();
        }

        [TestMethod]
        public void PostgreSQLTestUnsizedStringModelGeneratesSchema()
        {
            this.TestUnsizedStringModelGeneratesSchema();
        }

        [TestMethod]
        public async Task PostgreSQLTestKeylessProjectionLoads()
        {
            await this.TestKeylessProjectionLoads();
        }

        [TestMethod]
        public void PostgreSQLTestKeylessModelCannotBeMutated()
        {
            this.TestKeylessModelCannotBeMutated();
        }

        [TestMethod]
        public async Task PostgreSQLTestAutoGeneratedKeysAreTimeOrdered()
        {
            await this.TestAutoGeneratedKeysAreTimeOrdered();
        }

        [TestMethod]
        public void PostgreSQLTestKeyGeneratorIsPluggable()
        {
            this.TestKeyGeneratorIsPluggable();
        }
    }
}
