using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;

namespace OrpheusTests.MySQLTests
{
    [TestClass]
    [TestCategory(BaseTestClass.MySQLServerTests)]
    [DoNotParallelize]
    public class MySQLServerDependencyInjectionTests : DependencyInjectionTests
    {
        [TestInitialize]
        public void Setup()
        {
            this.DatabaseEngine = DbEngine.dbMySQL;
        }

        [TestMethod]
        public void MySQLServerTestSchemaAndModuleResolveFromTheDatabase()
        {
            this.TestSchemaAndModuleResolveFromTheDatabase();
        }

        [TestMethod]
        public void MySQLServerTestUnsizedStringModelGeneratesSchema()
        {
            this.TestUnsizedStringModelGeneratesSchema();
        }

        [TestMethod]
        public async Task MySQLServerTestKeylessProjectionLoads()
        {
            await this.TestKeylessProjectionLoads();
        }

        [TestMethod]
        public void MySQLServerTestKeylessModelCannotBeMutated()
        {
            this.TestKeylessModelCannotBeMutated();
        }

        [TestMethod]
        public async Task MySQLServerTestAutoGeneratedKeysAreTimeOrdered()
        {
            await this.TestAutoGeneratedKeysAreTimeOrdered();
        }

        [TestMethod]
        public void MySQLServerTestKeyGeneratorIsPluggable()
        {
            this.TestKeyGeneratorIsPluggable();
        }
    }
}
