using OrpheusAttributes;

namespace OrpheusDemoApi.Models;

/*
 * These four classes are the entire "mapping layer" of this sample. There is no fluent
 * configuration, no migrations folder and no context class — Orpheus reads the attributes below to
 * generate the DDL (see Schema/DemoSchema.cs) and to build every INSERT/UPDATE/DELETE at runtime.
 *
 * Table names default to the class name, so no [TableName] attribute is needed here. Note that
 * PostgreSQL folds unquoted identifiers to lower case, so these land in the database as "customer",
 * "product", "salesorder" and "salesorderline".
 *
 * The order aggregate is called SalesOrder rather than Order on purpose: ORDER is a reserved word in
 * PostgreSQL, and Orpheus emits table names unquoted in its CREATE TABLE statements, so a model
 * class named Order would produce `CREATE TABLE Order (...)` and fail to parse.
 */

/// <summary>
/// A customer. Referenced by <see cref="SalesOrder"/>.
/// </summary>
public class Customer
{
    /// <summary>
    /// [PrimaryKey] with no arguments means Orpheus generates the Guid on insert when the property
    /// is left at Guid.Empty. Pass isAutoGenerated:false to always supply the key yourself.
    /// </summary>
    [PrimaryKey]
    public Guid CustomerId { get; set; }

    /// <summary>[UniqueKey] adds a UNIQUE constraint; [Length] sizes the varchar column.</summary>
    [UniqueKey]
    [Length(30)]
    public string Code { get; set; } = string.Empty;

    [Length(120)]
    public string Name { get; set; } = string.Empty;

    [Length(250)]
    public string Email { get; set; } = string.Empty;
}

/// <summary>
/// A sellable product. Referenced by <see cref="SalesOrderLine"/>.
/// </summary>
public class Product
{
    [PrimaryKey]
    public Guid ProductId { get; set; }

    [Length(30)]
    public string Code { get; set; } = string.Empty;

    [Length(120)]
    public string Description { get; set; } = string.Empty;

    /// <summary>[DefaultValue] emits a DEFAULT clause in the generated DDL.</summary>
    [DefaultValue(0)]
    public double Price { get; set; }
}

/// <summary>
/// The master record of the order aggregate.
/// </summary>
public class SalesOrder
{
    [PrimaryKey]
    public Guid SalesOrderId { get; set; }

    /// <summary>
    /// [ForeignKey] emits a real FOREIGN KEY constraint and tells the schema engine that Customer
    /// must be created before SalesOrder.
    /// </summary>
    [ForeignKey(typeof(Customer), "CustomerId")]
    public Guid CustomerId { get; set; }

    public DateTime OrderDate { get; set; }

    [Length(50)]
    public string OrderNumber { get; set; } = string.Empty;
}

/// <summary>
/// The detail record of the order aggregate. <see cref="SalesOrderId"/> is deliberately never set by
/// the API layer — the module wires it up from the master record during Save(). See
/// Endpoints/SalesOrderEndpoints.cs.
/// </summary>
public class SalesOrderLine
{
    [PrimaryKey]
    public Guid SalesOrderLineId { get; set; }

    [ForeignKey(typeof(SalesOrder), "SalesOrderId")]
    public Guid SalesOrderId { get; set; }

    [ForeignKey(typeof(Product), "ProductId")]
    public Guid ProductId { get; set; }

    [DefaultValue(0)]
    public double Quantity { get; set; }

    public double Price { get; set; }

    public double TotalPrice { get; set; }
}
