<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>


  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>OrpheusORMAttributes</PackageId>
    <Title>OrpheusORM Attributes</Title>
    <Description>OrpheusORM schema creation/code first attributes.</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\net9.0\OrpheusAttributes.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net9.0\OrpheusAttributes.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrpheusInterfaces\OrpheusInterfaces.csproj" />
  </ItemGroup>

</Project>
