using System;

namespace OrpheusInterfaces.Core
{
    /// <summary>
    /// Generates the values Orpheus assigns to auto-generated <see cref="Guid"/> keys: model primary
    /// keys marked <c>[PrimaryKey(isAutoGenerated: true)]</c>, schema ids, and schema object unique
    /// keys.
    /// </summary>
    /// <remarks>
    /// The default implementation produces RFC 9562 UUIDv7 values, which embed a 48-bit millisecond
    /// timestamp in their high bits and therefore sort in creation order.
    /// <para>
    /// A caveat worth knowing before relying on that for index locality: SQL Server's
    /// <c>uniqueidentifier</c> does not compare bytes left to right — it orders by the last six
    /// bytes first — so time-ordered values are <b>not</b> sequential in a SQL Server index. The
    /// benefit applies to PostgreSQL's <c>uuid</c> and MySQL's binary/char storage. This is a
    /// property of the engine rather than of the value, and applies equally to ULIDs or any other
    /// time-ordered 128-bit scheme.
    /// </para>
    /// <para>
    /// Register a replacement with <c>AddOrpheusKeyGenerator&lt;T&gt;()</c> to change the scheme —
    /// for example back to random v4 values.
    /// </para>
    /// </remarks>
    public interface IOrpheusKeyGenerator
    {
        /// <summary>
        /// Returns a new key value.
        /// </summary>
        Guid NewKey();
    }
}
