using OrpheusDemoApi.Contracts;
using OrpheusDemoApi.Data;
using OrpheusDemoApi.Models;

namespace OrpheusDemoApi.Endpoints;

/// <summary>
/// Plain async CRUD over a single table — the smallest useful thing you can do with Orpheus.
/// </summary>
/// <remarks>
/// The pattern in every handler below is the same three steps:
/// <list type="number">
/// <item>get a connected database from the request-scoped <see cref="OrpheusSession"/>,</item>
/// <item>create a typed table for the model (<c>CreateTable&lt;Customer&gt;()</c> uses the class name
/// as the table name),</item>
/// <item>load, mutate the in-memory <c>Data</c> list through Add/Update/Delete, then
/// <c>SaveAsync</c>.</item>
/// </list>
/// Tables are <see cref="IDisposable"/>, hence the <c>using</c>. Nothing is written until Save, and
/// Save runs inside a transaction.
/// </remarks>
public static class CustomerEndpoints
{
    public static RouteGroupBuilder MapCustomerEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/customers").WithTags("Customers");

        group.MapGet("/", async (OrpheusSession session, CancellationToken ct) =>
        {
            var db = await session.ConnectAsync(ct);
            using var customers = db.CreateTable<Customer>();
            await customers.LoadAsync(ct);
            return Results.Ok(customers.Data);
        })
        .WithSummary("List all customers")
        .WithDescription("Loads the whole table with IOrpheusTable<Customer>.LoadAsync.");

        group.MapGet("/{id:guid}", async (Guid id, OrpheusSession session, CancellationToken ct) =>
        {
            var db = await session.ConnectAsync(ct);
            using var customers = db.CreateTable<Customer>();

            // Passing key values loads only the matching rows. The values are positional against the
            // table's key fields, which here is the single [PrimaryKey] property.
            await customers.LoadAsync([id], ct);

            var customer = customers.Data.FirstOrDefault();
            return customer is null ? Results.NotFound() : Results.Ok(customer);
        })
        .WithSummary("Get a customer by id");

        group.MapPost("/", async (CustomerRequest request, OrpheusSession session, CancellationToken ct) =>
        {
            var db = await session.ConnectAsync(ct);
            using var customers = db.CreateTable<Customer>();

            // CustomerId is left as Guid.Empty on purpose. Because [PrimaryKey] defaults to
            // isAutoGenerated:true and the property is a Guid, Orpheus generates the key during Save
            // and writes it back onto this instance — which is why it can be read out afterwards.
            var customer = new Customer
            {
                Code = request.Code,
                Name = request.Name,
                Email = request.Email,
            };

            customers.Add(customer);
            await customers.SaveAsync(ct);

            return Results.Created($"/api/customers/{customer.CustomerId}", customer);
        })
        .WithSummary("Create a customer")
        .WithDescription("Shows Orpheus generating the Guid primary key and assigning it back to the model.");

        group.MapPut("/{id:guid}", async (Guid id, CustomerRequest request, OrpheusSession session, CancellationToken ct) =>
        {
            var db = await session.ConnectAsync(ct);
            using var customers = db.CreateTable<Customer>();
            await customers.LoadAsync([id], ct);

            var customer = customers.Data.FirstOrDefault();
            if (customer is null)
            {
                return Results.NotFound();
            }

            customer.Code = request.Code;
            customer.Name = request.Name;
            customer.Email = request.Email;

            // Update queues the change against the loaded row; SaveAsync issues the UPDATE.
            customers.Update(customer);
            await customers.SaveAsync(ct);

            return Results.Ok(customer);
        })
        .WithSummary("Update a customer");

        group.MapDelete("/{id:guid}", async (Guid id, OrpheusSession session, CancellationToken ct) =>
        {
            var db = await session.ConnectAsync(ct);
            using var customers = db.CreateTable<Customer>();
            await customers.LoadAsync([id], ct);

            var customer = customers.Data.FirstOrDefault();
            if (customer is null)
            {
                return Results.NotFound();
            }

            customers.Delete(customer);
            await customers.SaveAsync(ct);

            return Results.NoContent();
        })
        .WithSummary("Delete a customer");

        return group;
    }
}
